name: CI

on:
  push:
    branches:
      - "**"
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: 'read'

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - uses: nrwl/nx-set-shas@v3
      - name: Setup Git
        run: |
          git config --global user.name "GitHub Bot"
          git config --global user.email "pipelines@aiviagroup.com"
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'
          check-latest:
      - run: pnpm install --frozen-lockfile
      - run: pnpm nx format:check --all # This command will be depricated by nx and replaced by a better option in the future
      - run: pnpm nx run-many -t lint --parallel=3
      - run: pnpm nx run-many -t build --parallel=3
      - run: pnpm nx run-many -t test --parallel=3
